version: 2.1

jobs:
  setup_wordpress:
    docker:
      - image: circleci/php:7.4-cli
    steps:
      - checkout

      # Baixa a imagem do WordPress
      - setup_remote_docker:
          version: 20.10.7
          
      - run:
          name: Baixando a imagem do WordPress
          command: docker pull wordpress:latest
          
      # Inicializa o container do WordPress
      - run:
          name: Iniciando o container do WordPress
          command: |
            docker run -d \
              --name wordpress \
              -p 8080:80 \
              -e WORDPRESS_DB_HOST=localhost \
              -e WORDPRESS_DB_USER=root \
              -e WORDPRESS_DB_PASSWORD=password \
              wordpress:latest
          
      # Verifica se o container está rodando
      - run:
          name: Verificando se o WordPress está em execução
          command: docker ps | grep wordpress

workflows:
  version: 2
  wordpress_workflow:
    jobs:
      - setup_wordpress
