version: 2.1

orbs:
  rancher_orbs: twinfo-io/rancher_orbs@0.0.5

jobs:
  build-web:
    docker:
      - image: cimg/base:stable  # Pode mudar a imagem base conforme necessário
    steps:
      - checkout
      
      - setup_remote_docker:
          version: 20.10.7  # Versão do Docker que o CircleCI usará

      - run:
          name: Install Docker Compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - rancher_orbs/upgrade:
          name: deploy-wordpress-rancher
          attach-workspace: true
          stack-definition: .circleci/docker-compose.yml
          stack-name: wordpress-stack
          env: default
          context: wordpressEnv


