version: 2.1
orbs:
  rancher_orbs: twinfo-io/rancher_orbs@0.0.5

jobs:
  build-web:
    steps:
    - checkout
    
      rancher_orbs/upgrade:
        name: deploy-wordpress-rancher
        stack-definition: .circleci/docker-compose.yml
        stack-name: wordpress-stack
        context:
          - wordpressEnv
    
workflows:
  version: 2
  wordpress_workflow:
    jobs:
      - setup_wordpress
